name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Black Check
      # You may pin to the exact commit or the version.
      # uses: jpetrucciani/black-check@a28a1107af4dc9bcdaa15beb8a81d4ad408891eb
      uses: jpetrucciani/black-check@23.7.0
      with:
        # File or directory to run black on
        path: .
        
    - name: python-flake8
      # You may pin to the exact commit or the version.
      # uses: julianwachholz/flake8-action@75749239077651dfd0ecbe405899cdcb0673ee8f
      uses: julianwachholz/flake8-action@v2.0.2
      with:
        # The name of the check to add annotations to. Generally the same as the job that uses this action
        checkName: python-flake8
        # Path to use for flake8
        path: .
        config: ./flake8.conf
        isTest: false
